name: Deploy to VDS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies and build frontend
        run: |
          cd agriculturae-react
          npm install
          npm run build

      - name: Deploy frontend to VDS
        run: |
          scp -r agriculturae-react/dist root@37.148.210.147:/var/www/agriculturae.com/

      - name: Deploy backend to VDS
        run: |
          ssh root@37.148.210.147 "cd agriculturae-be && git pull origin main && npm install && pm2 restart ecosystem.config.js --env production"
